-- Generated by Hydroxide's Upvalue Scanner: https://github.com/Upbolt/Hydroxide

local aux = loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/Upbolt/Hydroxide/revision/ohaux.lua"))()

local scriptPath = workspace.AlivePlayers.GeneralofAR.UI_Effects
local closureName = "Unnamed function"
local upvalueIndex = 4
local closureConstants = {
	[1] = "Variables",
	[2] = "Kills",
	[3] = "Value",
	[4] = "tick",
	[5] = aux.placeholderUserdataConstant,
	[6] = 3.5
}

local closure = aux.searchClosure(scriptPath, closureName, upvalueIndex, closureConstants)
local value = math.huge


-- DO NOT RELY ON THIS FEATURE TO PRODUCE 100% FUNCTIONAL SCRIPTS
debug.setupvalue(closure, upvalueIndex, value)