_G.sgod = true
while _G.sgod == true and wait() do
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohNumber1 = 100

workspace.Remotes.Heal:FireServer(ohNumber1)
end